### ISSUE TITLE
new column for crate command is in?

### ISSUE THREAD

**Issue by fdncred** [Nushell101/nu-stats#1]
I'm wondering if it's possible to add which crate these commands come from? The reason I ask is that I found myself doing filters on your csv like `where name !~ dfr` and then my next question to myself was, how do I filter this list with what is not in nu-cmd-extra.

What this does is allow us to focus on command that would be commonly used and also that we plan to support for 1.0. It may also force us to move commands from nu-cmd-extra to nu-commands to support them for 1.0 because more people use them than we thought.

Thanks for working on this!

**Comment by maxim-uvarov** [comment]
Darren, I'm glad that you found this research useful! I have some hypotheses on how to turn it into a tool that provides individual insights on enhancing nushell's usage for the end user. 

I didn't think much about the insights that developers might take from it. If you or someone else has more ideas on that, please let me know.

**Comment by maxim-uvarov** [comment]
> I'm wondering if it's possible to add which crate these commands come from? 

Now the only information that I use are these columns.
```
> help commands | columns
╭──────────────╮
│ name         │
│ category     │
│ command_type │
│ usage        │
│ params       │
│ input_output │
│ search_terms │
╰──────────────╯
```

I know very little about internals of nushell (though I would be glad to learn more). So if you could provide details, on how I can extract such data - it's very likely that I could incorporate them into reports.

**Comment by maxim-uvarov** [comment]
```sh
> help commands | columns
```

And because the 'aggregate-submissions' script filters commands based on this data, aggregated reports now lack information about commands that are not available in the host's 'help commands', even though they might be available in the users' submissions.

And that's why the [currently published aggregateds_stats files](https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/main/aggregated_stats/) are missing the `extra` crate commands, as I don't have it in my nushell (I develop solutions for users, who are primarily supposed to install nushell using package managers, and the extra package is not available there).

**Comment by fdncred** [comment]
I'm not sure really. We don't expose that information, but I know you can do something crazy like this, although I'm not sure it works across all platforms.

1. Get the hex representation of the command name
```nushell
❯ 'math sin' | into binary
Length: 8 (0x8) bytes | printable whitespace ascii_other non_ascii
00000000:   6d 61 74 68  20 73 69 6e                             math sin
```
2. search for those hex bytes in the nushell binary
```nushell
❯ open ~\.cargo\bin\nu.exe | bytes index-of 0x[6d 61 74 68 20 73 69 6e]
38161407
```
3. Take that byte index, add 300 to it
```nushell
❯ open ~\.cargo\bin\nu.exe | bytes at 38161407..38161707
Length: 300 (0x12c) bytes | printable whitespace ascii_other non_ascii
00000000:   6d 61 74 68  20 73 69 6e  68 52 65 74  75 72 6e 73   math sinhReturns
00000010:   20 74 68 65  20 68 79 70  65 72 62 6f  6c 69 63 20    the hyperbolic
00000020:   73 69 6e 65  20 6f 66 20  74 68 65 20  6e 75 6d 62   sine of the numb
00000030:   65 72 2e 74  72 69 67 6f  6e 6f 6d 65  74 72 79 68   er.trigonometryh
00000040:   79 70 65 72  62 6f 6c 69  63 41 70 70  6c 79 20 74   yperbolicApply t
00000050:   68 65 20 68  79 70 65 72  62 6f 6c 69  63 20 73 69   he hyperbolic si
00000060:   6e 65 20 74  6f 20 31 31  20 7c 20 6d  61 74 68 20   ne to 11 | math
00000070:   73 69 6e 68  69 6e 74 65  72 6e 61 6c  20 65 72 72   sinhinternal err
00000080:   6f 72 3a 20  65 6e 74 65  72 65 64 20  75 6e 72 65   or: entered unre
00000090:   61 63 68 61  62 6c 65 20  63 6f 64 65  63 72 61 74   achable codecrat
000000a0:   65 73 5c 6e  75 2d 63 6d  64 2d 65 78  74 72 61 5c   es\nu-cmd-extra\
000000b0:   73 72 63 5c  65 78 74 72  61 5c 6d 61  74 68 5c 73   src\extra\math\s
000000c0:   69 6e 68 2e  72 73 00 00  00 9b 60 46  42 01 00 00   inh.rs000×`FB•00
000000d0:   00 2a 00 00  00 00 00 00  00 45 00 00  00 16 00 00   0*0000000E000•00
000000e0:   00 6d 61 74  68 20 74 61  6e 68 52 65  74 75 72 6e   0math tanhReturn
000000f0:   73 20 74 68  65 20 68 79  70 65 72 62  6f 6c 69 63   s the hyperbolic
00000100:   20 74 61 6e  67 65 6e 74  20 6f 66 20  74 68 65 20    tangent of the
00000110:   6e 75 6d 62  65 72 2e 41  70 70 6c 79  20 74 68 65   number.Apply the
00000120:   20 68 79 70  65 72 62 6f  6c 69 63 20                 hyperbolic
```
4. Notice in the string above there is nu-cmd-extra.

> And that's why the [currently published aggregateds_stats files](https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/main/aggregated_stats/) are missing the extra crate commands, as I don't have it in my nushell (I develop solutions for users, who are primarily supposed to install nushell using package managers, and the extra package is not available there).

If you're doing data analysis it's really better to compile with `cargo install nu --features=extra,dataframe,mimalloc`.

**Comment by fdncred** [comment]
Here's another idea. If you have the source code, you could just do `rg 'math sin'` and grab the path from the results. The path will tell you the crate.

**Comment by maxim-uvarov** [comment]
> Here's another idea. If you have the source code, you could just do rg 'math sin' and grab the path from the results. The path will tell you the crate.

Sure, I can do that. I'm not sure when exactly, but hopefully soon.

**Comment by fdncred** [comment]
I have an idea about writing a custom command to search for this. I just have to carve out some time.

**Comment by maxim-uvarov** [comment]
@fdncred so I got this in a folder …/nushell/crates:
`rg 'fn name.*\n.*"(.*)"?' -U | lines | where $it !~ 'fn name\(' | parse "{crate}: {fn}" | str trim | sort-by crate | upsert fn {|i| $i.fn | str replace -a '"' ''}`

482 functions so far

[crates20230912.csv](https://github.com/maxim-uvarov/nu-commands-frequency-stats/files/12586193/crates20230912.csv)

Briefly I found this two functions strange

<img width="818" alt="image" src="https://github.com/maxim-uvarov/nu-commands-frequency-stats/assets/4896754/52a0e26e-89b9-4e52-9f1d-f80af562e814">

Are they ok?

**Comment by fdncred** [comment]
I'm guessing you could filter out the tests and nu-plugin like `where crate !~ tests or crate !~ nu-plugin`. However, the part that is missing is the plugins. They're all in the nu_plugin_<name> crates. You can mostly find these with `rg 'PluginSignature::build'`.  But ya, this is a great start! Now you just need to parse the crate name which should be the first path after `crates`.

**Comment by maxim-uvarov** [comment]
I have written a script that parses crates through GitHub tags. 

I source it being inside the crates folder. 

```sh
#crates_parsing

def parse_crates [
    tag?
] {
    let $tag_default = ($tag | default (git tag | lines | last))
    git checkout $tag_default

    let $plugin_crates = (rg 'PluginSignature::build\("(.*)"\)' --json | from json -o | where type == 'match' | get data | select path lines | flatten | upsert command {|i| $i.lines_text | lines | get 0 | str replace -r '(?m).*"(.*?)".*' '$1'} | reject lines_text | upsert crate {|i| $i.text | path split | get 0} | reject text); $plugin_crates
    let $main_crates = (rg 'fn name.*\n.*"(.*)"?' -U --json | from json -o | where type == 'match' | get data | select path lines | flatten | upsert command {|i| $i.lines_text | lines | get 1 | str replace -r '(?m).*"(.*?)".*' '$1'} | reject lines_text | upsert crate {|i| $i.text | path split | get 0} | reject text ); $main_crates

    $main_crates | append $plugin_crates | upsert tag $tag
}

let $commands_in_tags = (git tag | lines | where (($it | str length) == 6) | last 10 | each {|i| parse_crates $i})

let $commands_with_first_tag = ($commands_in_tags | flatten | group-by command | values | each {|i| $i | get 0} | flatten);

let $commands_missing = (help commands | where command_type in ['builtin' 'keyword'] | get name | where $it not-in $commands_with_first_tag.command)

$commands_with_first_tag
```

I get a such table 
[commands_by_tags.csv](https://github.com/maxim-uvarov/nu-commands-frequency-stats/files/12609861/commands_by_tags.csv)

@fdncred Do you think it has any usefulness?

**Comment by maxim-uvarov** [comment]
I found that it is missing some commands (`$commands_missing`). I will check tomorrow how they differ from others, so our `rg` scripts doesn't catch them.

```
> $commands_missing
╭────────────────╮
│ dfr agg-groups │
│ dfr cache      │
│ dfr count      │
│ dfr expr-not   │
│ dfr implode    │
│ dfr max        │
│ dfr mean       │
│ dfr median     │
│ dfr min        │
│ dfr reverse    │
│ dfr std        │
│ dfr sum        │
│ dfr var        │
│ hash md5       │
│ hash sha256    │
╰────────────────╯
```

p.s. I still don't have extra feature. So there might be more commands missing

**Comment by fdncred** [comment]
Cool!  This is looking great so far. I think that csv will be very useful for what we're trying to do. I figure we'll be able to use it with your original list using the join command to find which crate things are in.

**Comment by maxim-uvarov** [comment]
I didn't know that `join` in nushell already exists. Or I forgot and [never used it](https://github.com/maxim-uvarov/nu-commands-frequency-stats/commit/0fb6fafad4825c8edaa2db93b29314b2112a0f71)...
Nice discovery, thanks.

So, I've updated the script that greps through tags, and I've updated the resulting CSV. 
Both are in the folder: https://github.com/maxim-uvarov/nu-commands-frequency-stats/tree/main/crates_parsing

Next time, I will use this data in the main script. I like what is coming out of it!

**Comment by fdncred** [comment]
nice work! looks great!

**Comment by maxim-uvarov** [comment]
@fdncred I've updated the aggregated stats, and now it includes crate info, as well as some deprecated commands (although I expected their number to be higher).

**Comment by maxim-uvarov** [comment]
@fdncred I've updated the aggregated stats, and now it includes crate info, as well as some deprecated commands (although I expected their number to be higher).

https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/main/aggregated_stats/aggregated-freq-stats20230918.csv

**Comment by fdncred** [comment]
> @fdncred I've updated the aggregated stats, and now it includes crate info, as well as some deprecated commands (although I expected their number to be higher).
> 
> https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/main/aggregated_stats/aggregated-freq-stats20230918.csv

oh wow, this is very nice! I'm not asking for a change, but it's odd that the tags only go back to 0.39. We clearly had some of these command before that.

**Comment by maxim-uvarov** [comment]
> I'm not asking for a change, but it's odd that the tags only go back to 0.39. We clearly had some of these command before that.

I was filtering tags for some reason [from 0.39](https://github.com/maxim-uvarov/nu-commands-frequency-stats/commit/2a3951535750745f408919d55ff4a8552e8c4662#diff-220eb4bf0882ef10854ede7a66747d8af677b6f3b146a6767ed54ced66e18bf3). Now everything should be precise:)

**Comment by fdncred** [comment]
I see it goes back to 0.11.0, which is almost all the way. The first release was 0.2.0. There were quite a few commands way back then https://github.com/nushell/nushell/tree/0.2.0/src/commands. 

I'm not really sure it's important to have the first tag the commands were used in, but if we're going to have them, I'd hope they would be accurate. If it's too much trouble, don't worry about it. You've already done a ton of work on this, and I don't mean to be critical.

**Comment by maxim-uvarov** [comment]
No truble at all. You can check tags by yourself.

Seems like the way the commands was declared was different. Or they were in another path. Otherwise `rg` whould rip them out. 

```
open crates_parsing/cmds_by_crates_and_tags.csv | first 30
╭────────────name─────────────┬───crate───┬─first_tag─┬─last_tag─╮
│ ..                          │ nu-parser │ 0.7.0     │ 0.8.0    │
│ AnyBlockShape               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ AnyExpressionShape          │ nu-parser │ 0.7.0     │ 0.8.0    │
│ AnyExpressionStartShape     │ nu-parser │ 0.7.0     │ 0.8.0    │
│ BareShape                   │ nu-parser │ 0.7.0     │ 0.8.0    │
│ BareTailShape               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ColorableDotShape           │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ColumnPathShape             │ nu-parser │ 0.7.0     │ 0.8.0    │
│ CommandHeadShape            │ nu-parser │ 0.7.0     │ 0.8.0    │
│ CommandShape                │ nu-parser │ 0.7.0     │ 0.8.0    │
│ CommandTailShape            │ nu-parser │ 0.7.0     │ 0.8.0    │
│ DelimitedShape              │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ExpressionContinuationShape │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ExpressionListShape         │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ExternalExpressionShape     │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ExternalTokensShape         │ nu-parser │ 0.7.0     │ 0.8.0    │
│ FilePathShape               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ InfixShape                  │ nu-parser │ 0.7.0     │ 0.8.0    │
│ IntShape                    │ nu-parser │ 0.7.0     │ 0.8.0    │
│ InternalCommandHeadShape    │ nu-parser │ 0.7.0     │ 0.8.0    │
│ MaybeSpaceShape             │ nu-parser │ 0.7.0     │ 0.8.0    │
│ MemberShape                 │ nu-parser │ 0.7.0     │ 0.8.0    │
│ NumberShape                 │ nu-parser │ 0.7.0     │ 0.8.0    │
│ PathTailShape               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ PatternShape                │ nu-parser │ 0.7.0     │ 0.8.0    │
│ PipelineShape               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ RangeShape                  │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ShorthandBlock              │ nu-parser │ 0.7.0     │ 0.8.0    │
│ ShorthandPath               │ nu-parser │ 0.7.0     │ 0.8.0    │
│ SpaceShape                  │ nu-parser │ 0.7.0     │ 0.8.0    │
╰────────────name─────────────┴───crate───┴─first_tag─┴─last_tag─╯
```

**Comment by fdncred** [comment]
ok, understood. it's tricky trying to go back in time. so much has changed since then. appreciate your help with this.

**Comment by maxim-uvarov** [comment]
it's pleasure for me to work with data, and it's joyful to be useful.

**Comment by maxim-uvarov** [comment]
> I see it goes back to 0.11.0, which is almost all the way. The first release was 0.2.0. There were quite a few commands way back then https://github.com/nushell/nushell/tree/0.2.0/src/commands.

@fdncred So I checked `0.2.0` manually, and found that there were no crates folder at all. And our script parses data from that folder. I found that `0.7.0` was the first tag with the crates folder.

I guess, I will write a manual script to update the `first tag` column, with results from the `src` folder to be more precise.

**Comment by fdncred** [comment]
I'm not worried about it. I'm fine with leaving it the way it is. You've already done so much excellent work.

**Comment by maxim-uvarov** [comment]
any way, it was easy:)
https://github.com/Nushell101/nu-stats/commit/2a51b7192776457f49dfcf01a0e9e3a9df2f2d82

**Comment by fdncred** [comment]
oh that does look pretty easy. loving this file https://github.com/Nushell101/nu-stats/blob/main/script_results/aggregated-submissions.csv
