### ISSUE TITLE
repl vs script

### ISSUE THREAD

**Issue by fdncred** [Nushell101/nu-stats#5]
I had another thought. These stats currently are based on what people have provided us from their history. That means all these commands were typed into the repl. That's great but it's only one picture of what is used. Another view is scripts. People use commands in scripts in a very different way than they use their repl. 

I'm betting if we had a script that read scripts, like in the nu_scripts repo, we'd get a different picture of which commands are used. For instance, I'm sure `ls` is used in scripts, but I'd bet that it's used way more in the repl.

**Comment by maxim-uvarov** [comment]
@fdncred, I think We already have what you suggest 

1. There is a [function](https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/d68c9d4031c3e9d849dd8c23aa32bcee57e1a505/v2-nu-commands-freq.nu#L63), that calculates stats from files.
2. Using this function I already calculated stats on `nu-std` and `nu-scripts`. You can find the results with preffix `surrogate` in [the submissions folder](https://github.com/maxim-uvarov/nu-commands-frequency-stats/tree/main/results_submissions)
3. Moreover, [aggregated stas](https://github.com/maxim-uvarov/nu-commands-frequency-stats/blob/main/aggregated_stats/aggregated-freq-stats20230918.csv) already includes this data :)

**Comment by maxim-uvarov** [comment]
I definetly need to docuemnt the script. But seems like till the end of this week I'm occupied with some other task

**Comment by maxim-uvarov** [comment]
in the `f_n_by_user` `nu_scripts` is the first column, and `nu_std` is third from the right.
<img width="1291" alt="image" src="https://github.com/maxim-uvarov/nu-commands-frequency-stats/assets/4896754/826843e3-1254-4855-9dc9-a1521bdff734">

**Comment by fdncred** [comment]
great! I didn't realize you were already doing that. Thanks for the info!
